# <center> Funções Numpy </center>

## BasicToolBox  - Numpy II

In [215]:
import numpy as np

## ``linspace`` Numpy

* Retorna números com espaçamento uniforme em um intervalo especificado.

In [216]:
# Criando um intervalo de valores entre 1 e 5 com 8 valores nesse intervalo 
intervalo = np.linspace(1,5, 8)
print(intervalo)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [217]:
type(intervalo)

numpy.ndarray

In [218]:
# Criando um intervalo de valores entre 1 e 5 com 8 valores nesse intervalo
for x in np.linspace(1,5, 8):
    print(x)
type(x)

1.0
1.5714285714285714
2.142857142857143
2.7142857142857144
3.2857142857142856
3.8571428571428568
4.428571428571429
5.0


numpy.float64

## ``arange`` Numpy 

* Retorna valores espaçados uniformemente dentro de um determinado intervalo.

In [219]:
# Gerando valores de 1 até 9
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
# Gerando Valores de 0 até 9 de 2 em 2
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [221]:
# Gerando Valores de 1 até 9 pulando de 2 em 2 
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [222]:
# Criando um intervalo de 10 elementos, sendo valores vde 0 a 9
np_arange = np.arange(10)
print(np_arange)

[0 1 2 3 4 5 6 7 8 9]


In [223]:
# Criando um intervalo de 10 elementos, sendo separados os valores pares 
for x in np_arange:
    if x % 2 == 0:
        print(x, end='  ')

0  2  4  6  8  

In [224]:
# Criando um intervalo de 10 elementos, sendo separados os valores ímpares
for x in np_arange:
    if x % 2 != 0:
        print(x)

1
3
5
7
9


## Indexação

In [225]:
# Craindo array para exemplo "a"
array_a = np.array([1,2,3])
print(array_a,'\n')

# Craindo array para exemplo "b"
array_b = np.array([[2,3,4],[5,6,7]])
print(array_b)

[1 2 3] 

[[2 3 4]
 [5 6 7]]


In [226]:
# buscando elemento pelos indices 
print(array_a[0])
print(array_b[0,1])
print(array_b[1,2])

1
3
7


## <center>  Operadores de Condições Python/Matematicos com Array </center>

In [227]:
# Operador matematico de aplicação comparativa entre inteiros
print(3 > 1)
# Retorno Booleano

True


In [228]:
# Operador matematico de aplicação comparativa entre intiro (Escalar) e o "array_a"
print(array_a > 1)
# Retorno Booleano

[False  True  True]


In [229]:
# Operador matematico de aplicação comparativa entre intiro (Escalar) e o "array_b"
print(array_b > 3)
# Retorno Booleano

[[False False  True]
 [ True  True  True]]


In [230]:
# Operador Python de Igualdade aplicado entre inteiro e o "array_a"
array_a[array_a == 1]
# Busca elemento igual no array

array([1])

In [231]:
# Operador Python de Igualdade aplicado entre inteiro e o "array_b"
array_b[array_b == 5]
# Busca elemento igual no array

array([5])

### ``where`` Array Numpy

* Retorna elementos escolhidos de x ou y dependendo da condição

In [232]:
# Retorna elementos escolhidos de x ou y dependendo da condição .
np.where(array_a > 1)

(array([1, 2], dtype=int64),)

## <center> Funções Estatísticas Básicas Numpy </center>

## ``mean`` Array Numpy

* Calcule a média aritmética ao longo do eixo especificado.

In [233]:
# Função numpy para obter a média aritmética do "array_a"
media_a = np.mean(array_a)
print(f'Média do Array "a": {media_a} \n')

# Função numpy para obter a média aritmética do "array_b"
media_b = np.mean(array_b)
print(f'Média do Array "b": {media_b} ')

Média do Array "a": 2.0 

Média do Array "b": 4.5 


## ``median`` Array Numpy

* Retorna a Mediana do conjunto de valores

In [234]:
# Calculando a Mediana com numpy
np.median([1,2,3,4])

2.5

## ``std`` Array Numpy

* Calcule o desvio padrão ao longo do eixo especificado.

In [235]:
# Função numpy para obter desvio padrão "array_a"
desvio_a = np.std(array_a)
print(f'Desvio Padrão no Array "a": {desvio_a:.2f} \n')
# Limitando o resultado do desvio padrão no array_a ha duas casas decimais 

# Função numpy para obter desvio padrão "array_b"
desvio_b = np.std(array_b)
print(f'Desvio Padrão no Array "b": {desvio_b:.2f} \n')
# Limitando o resultado do desvio padrão no array_b ha duas casas decimais 

Desvio Padrão no Array "a": 0.82 

Desvio Padrão no Array "b": 1.71 



## ``var`` Array Numpy

* Calcule a variação ao longo do eixo especificado.

In [236]:
# Função numpy para obter a variância no "array_a"
var_a = np.var(array_a)
print(f'Variância no Array "a": {var_a:.2f}')
# Limitando o resultado da variância no array_a ha duas casas decimais 

# Função numpy para obter a variância no "array_b"
var_b = np.var(array_b)
print(f'Variância no Array "b": {var_b:.2f}')
# Limitando o resultado da variância no array_b ha duas casas decimais 

Variância no Array "a": 0.67
Variância no Array "b": 2.92


## <center> Manipulando Arrays com hstack e vstack </center>

In [237]:
# Criando Arrays para Exemplificar
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.array([1,1,1])
print(a,'\t',b,'\t',c)

[1 2 3] 	 [2 3 4] 	 [1 1 1]


## ``vstack`` Array Numpy

* Empilhe matrizes em sequência verticalmente (linha).

In [238]:
# Criando Arrays para Exemplificar
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.array([1,1,1])

# 1º Opção - Empilhe matrizes em sequência verticalmente (linha).
array_vstack_01 = np.vstack((c,a,b))
# Criando Arrays para Exemplificar
print(array_vstack_01)

[[1 1 1]
 [1 2 3]
 [2 3 4]]


In [239]:
# Criando Arrays para Exemplificar
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.array([1,1,1])

# 2º Opção - Empilhe matrizes em sequência verticalmente (linha).
array_vstack_02 = np.vstack((c,a))
print(array_vstack_02)

[[1 1 1]
 [1 2 3]]


In [240]:
# Craindo Matriz para exemplificação
a = np.array([[1,2,3],[4,5,6]])

# Criando Vetor para exemplificação
b = np.array([2,3,4])

# Concatendo por meio do np.vstack()
vstack = np.vstack((a,b))
print(vstack)

[[1 2 3]
 [4 5 6]
 [2 3 4]]


In [241]:
# Confirmando o Tipo Primitivo do Dado
type(vstack)

numpy.ndarray

## ``hstack`` Array Numpy

* Empilhe matrizes em sequência horizontalmente (em colunas).

In [242]:
# Criando Arrays para Exemplificar
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.array([1,1,1])

# Empilhe matrizes em sequência horizontalmente (em colunas)
array_hstack_01 = np.hstack((c,a,b))
print(array_hstack_01)

[1 1 1 1 2 3 2 3 4]


In [243]:
# Criando Arrays para Exemplificar
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.array([1,1,1])

# Empilhe matrizes em sequência horizontalmente (em colunas)
array_hstack_01 = np.hstack((c,a))
print(array_hstack_01)

[1 1 1 1 2 3]


## ``append`` Array Numpy

* Acrescente valores ao final de uma matriz.

In [244]:
# Adicionando valores por meio do append
array_apend= np.append(a,b)
print(array_apend)

[1 2 3 2 3 4]


# <center> Concatenação de Arrays </center>

In [245]:
# Craindo Matriz para exemplificação
a = np.array([[1,2,3],[4,5,6]])

# Criando Vetor para exemplificação
b = np.array([2,3,4])

# Concatenando por meio do np.append() Matriz e Vetor
apend = np.append(a,b)
apend

array([1, 2, 3, 4, 5, 6, 2, 3, 4])

In [246]:
# Confirmando o Tipo Primitivo do Dado
type(apend)

numpy.ndarray

## ``reshape`` Array Numpy

* Cria uma nova forma a um array sem alterar seus dados.

In [247]:
# Craindo Matriz para exemplificação
a = np.array([[1,2,3],[4,5,6]])

# Criando Vetor para exemplificação e remodelando seu formato de "linhas" para "colunas"
b = np.array([2,3,4]).reshape(1,3)

# Concatendo por meio do np.append()
resh_apend = np.append(a,b, axis=0)
resh_apend

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

In [248]:
# Craindo Matriz para exemplificação
a = np.array([[1,2,3],[4,5,6]])

# Criando Vetor para exemplificação
b = np.array([2,3,4])

# Concatendo por meio do np.append() e remolando para uma matriz 3x3 = 9
resh_apend = np.append(a,b)
resh_apend.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

In [249]:
# Confirmando o Tipo Primitivo do Dado
type(resh_apend)

numpy.ndarray

In [250]:
# Craindo vetor com 9 elementos para exemplificação
a = np.array([0,1,2,3,4,5,6,7,8])
print(a)

[0 1 2 3 4 5 6 7 8]


In [251]:
# Remodelando o formato de vetor para Matriz3x3 =- 9 elementos
array2D_1 = a.reshape((3,3))
print(array2D_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## ``concatenate`` Array Numpy

* Juntar uma sequência de matrizes ao longo de um eixo existente.

In [252]:
# Craindo vetor com 9 elementos para exemplificação e remodelando para o formato de matriz 3x3 = 9
array2D_1 = np.array([0,1,2,3,4,5,6,7,8]).reshape((3,3))

# Craindo vetor com 9 elementos para exemplificação e remodelando para o formato de matriz 3x3 = 9
array2D_2 = np.array([10,11,12,13,14,15,16,17,18]).reshape((3,3))

# Concatendo por meio de np.concatente()
np.concatenate((array2D_1, array2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [253]:
# Craindo vetor com 9 elementos para exemplificação
array2D_1 = np.array([0,1,2,3,4,5,6,7,8])

# Craindo vetor com 9 elementos para exemplificação
array2D_2 = np.array([10,11,12,13,14,15,16,17,18])

# Concatendo  em uma linha por meio de np.concatente()
np.concatenate((array2D_1, array2D_2)).reshape((6,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [254]:
# Craindo vetor com 9 elementos para exemplificação e remodelando para o formato de matriz 3x3 = 9
array2D_1 = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)

# Craindo vetor com 9 elementos para exemplificação e remodelando para o formato de matriz 3x3 = 9
array2D_2 = np.array([10,11,12,13,14,15,16,17,18]).reshape(3,3)

# Concatendo  em uma linha por meio de np.concatente()
np.concatenate((array2D_1, array2D_2), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

# <center> Funções Matematicas Numpy </center>

## ``sum`` Array numpy

* Retorna a soma do conjunto de valores

In [256]:
# Calculando a soma de todos os valores com numpy
np.sum([1,2,3,4])

10

## ``mod`` Array Numpy

* Retorna o restante da divisão elemento a elemento.

In [267]:
lista1 =[1,2,3]

lista2 = [4,5,6]

print(np.mod(lista2,lista1))
np.mod(lista2,lista1)

[0 1 0]


array([0, 1, 0], dtype=int32)

In [268]:
%%time
print('Fim !!')

Fim !!
Wall time: 0 ns
