# <center> Funções Bsicas Numpy </center>

## BasicToolBox  - Numpy I

In [2]:
import numpy as np

In [137]:
# lista para exemplo
lista = [1,2,3]

print(lista)

[1, 2, 3]


## ``Array`` Numpy

* Cria uma Matriz ou Vetor

In [138]:
# Craindo um array
np_array = np.array(lista, dtype = float)

# Verificando o Tipo Primitivo deste objeto numpy
print(type(np_array), '\n')


# Varificando os valor no array( Vetor ou Matriz)
print(np_array)

<class 'numpy.ndarray'> 

[1. 2. 3.]


In [139]:
# Esta função python estruturado com o "for", irá itarar em os valores do array
for i in range(len(lista)):
    lista[i] *= 2
print(lista)

# Craindo um looping com a quantidades de elementos na lista
# Multiplicando cada valor da lista, de acordo com a posição na contagem, por 2

[2, 4, 6]


In [140]:
# Repetindo duas vezes a lista
print(lista*2)
# 2,4,6 e novamente 2,4,6

[2, 4, 6, 2, 4, 6]


In [141]:
# Multiplicando cada valor do Array por 2
print(np_array * 2)

[2. 4. 6.]


## ``ndim`` Array Numpy

* Retorna o número de dimensões da matriz.

In [142]:
# Verificando o Nº de Dimensões
np_array.ndim
# este é um objeto numpy.array de uma dimensão

1

## ``shape`` Array Numpy

* Retorne a forma de um array

In [143]:
# Verificando a forma deste objeto numpy.array
np_array.shape
# Apenas três linhas, em uma unica dimensão

(3,)

##  ``size`` Array Numpy

* Número de elementos na matriz.

In [144]:
# Verificando o Nº de lementos no array
print(np_array.size)
# São tres elementos no array, 

print(np_array)
# Os valores 1,2,3 são os tes elementos 

print(np_array.shape)

3
[1. 2. 3.]
(3,)


## ``zeros`` Array Numpy

In [145]:
# Criando Array de zero 0
z = np.zeros((3,3), float)
print(z,'\n')

# Verificando o Nº de Dimensões
print(z.ndim)
# Duas dimensões

print()

# Formato do Array
print(z.shape)
# 3 Linhas e 3 Colunas

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

2

(3, 3)


## ``ones`` Array Numpy

In [146]:
# Criando Array de uns 1
u = np.ones((3,3), int)
print(u, '\n')

# Verificando o Nº de Dimensões
print(u.ndim)
# Duas dimensões
print()

# Formato do Array
print(u.shape)
# 3 Linhas e 3 Colunas

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

2

(3, 3)


## ``identity`` Array Numpy

* Retona a matriz identidade 

In [147]:
# Criando uma Matriz Identidade
i = np.identity(2)

# Verificando a  Matriz identidade
print(i,'\n')

# Verificando o Nº de Dimensões
print(i.ndim)
# Duas dimensões
print()

# Formato do Array
print(i.shape)
# 2 Linhas e 2 Colunas

[[1. 0.]
 [0. 1.]] 

2

(2, 2)


## ``full`` Array Numpy 

* Retorna uma nova matriz de determinado formato e tipo, preenchida com ``fill_value``(valor de preenchimento).

In [148]:
# Criar Matriz com todos os valores iguais
np.full((3,3), 52)

array([[52, 52, 52],
       [52, 52, 52],
       [52, 52, 52]])

## ``np.random`` Array Numpy

* Módulo implementa geradores de números pseudo-aleatórios

In [4]:
np.random()

TypeError: 'module' object is not callable

## ``random.rand`` Array Numpy

* Valores aleatórios em uma determinada forma

In [149]:
# Criar uma matriz com 4 por 2 com valores aleatorios entre 0 e 1
np.random.rand(4,2)

array([[0.37849214, 0.95454573],
       [0.38959295, 0.89642685],
       [0.23048084, 0.69403522],
       [0.38534729, 0.25732938]])

## ``random.randint`` Array Numpy

* Retorna inteiros aleatórios da distribuição “uniforme discreta” do dtype especificado no interval

In [150]:
# Criar uma Matriz 3 por 3 com valores aleatorios entre -4 e 8
np.random.randint(-4, 8, size=(3,3))

array([[-2, -2,  4],
       [ 6, -3, -2],
       [ 6,  2, -4]])

## <center> Manipulando Dimensões de um Array </center>

## ``reshape`` Array Numpy

* Uma nova forma a um array sem alterar seus dados.

In [151]:
# Craindo uma Matriz com 2 linhas e 6 colunas
narray = np.full((2,6),0.45)
print(f'Matriz 2x6 :\n {narray}\n\n')
# 2 * 6 = 12

# Aplicando a função numpy "reshape()" transformar em uma Matriz de 3 linhas e 4 colunas
narray = narray.reshape(3,4)
print(f'Matriz 3x4 \n {narray}')
#  3 * 4 = 12

Matriz 2x6 :
 [[0.45 0.45 0.45 0.45 0.45 0.45]
 [0.45 0.45 0.45 0.45 0.45 0.45]]


Matriz 3x4 
 [[0.45 0.45 0.45 0.45]
 [0.45 0.45 0.45 0.45]
 [0.45 0.45 0.45 0.45]]


In [152]:
narray.shape

(3, 4)

## ``ravel`` Array Numpy

* Retorna uma matriz achatada contígua. Uma matriz 1-D, contendo os elementos da entrada, é retornada.

In [153]:
# Criar uma uma matriz achatada contígua. "np.ravel()"
arr = (narray.ravel())
print(arr)
print()
print(arr.shape)
# transfoma a matriz em uma linha

[0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.45]

(12,)


## <center> Fatiamento em Arrays </center>

In [154]:
lista = [[0,1,2,3], [4,5,6,7],[8,9,10,11]]
print(lista)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [155]:
lista[1][1]

5

In [156]:
mat = np.array(lista)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
mat[1][1]

5

In [158]:
mat[0, :3]

array([0, 1, 2])

In [159]:
mat[0][:3]

array([0, 1, 2])

In [160]:
mat[0, 0:3]

array([0, 1, 2])

In [161]:
mat.shape

(3, 4)

In [162]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
mat[0,0]

0

In [164]:
mat[0,0] = 100

In [165]:
mat

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [166]:
mat[0,0]

100

In [167]:
mat[:, 0]

array([100,   4,   8])

In [168]:
mat[:, 0] = [200, 8, 16]

In [169]:
mat[:,0]

array([200,   8,  16])

In [170]:
mat

array([[200,   1,   2,   3],
       [  8,   5,   6,   7],
       [ 16,   9,  10,  11]])

## <center> Operações Matemáticas com Arrays </center>

In [171]:
# Craindo Array para exemplificação
array_ex2 = np.array([1,2,3,4])
print(array_ex2)

[1 2 3 4]


In [172]:
# Soma de Array por Escalar
print(array_ex2 + 2)

[3 4 5 6]


In [173]:
# Subtração de Array por Escalar
print(array_ex2 - 2)

[-1  0  1  2]


In [174]:
# Multiplicação de Array por Escalar
print(array_ex2 * 2)

[2 4 6 8]


In [175]:
# Divisão de Array por Escalar
print(array_ex2 / 2)

[0.5 1.  1.5 2. ]


In [176]:
# Exponenciação de Array por Escalar
print(array_ex2 ** 2)

[ 1  4  9 16]


In [177]:
# Extraindo Cosseno do Array
print(np.cos(array_ex2))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


# <center> Exemplos </center>

In [178]:
# Craindo Array para exemplificação
array_ex = np.array([[1,4,3],[4,5,6]])
print(array_ex)

[[1 4 3]
 [4 5 6]]


In [179]:
# 1º Opção - Percorrendo cada elemento do array
for num in array_ex:
    for i in num:
        print(i)

1
4
3
4
5
6


In [180]:
# 2º Opção - Percorrendo cada elemento do array
for i in range(array_ex.shape[0]):
    for j in range(array_ex.shape[1]):
        print(array_ex[i,j])

1
4
3
4
5
6


## ``ndenumerate``  Numpy

* É um iterador de índice multidimensional

In [181]:
# 3º Opção - Percorrendo cada elemento do array
for index, x in np.ndenumerate(array_ex):
    print(index, x)

(0, 0) 1
(0, 1) 4
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [182]:
# Verificando a forma do array
array_ex.shape

(2, 3)

In [184]:
# Percorrer cada elemento do Array Bidimensional e somar os elementos impares
arr_ = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## ``append``  Array Numpy

* Acrescente valores ao final de uma matriz.

In [187]:
impar = [] 

for i in range(arr_.shape[0]):
    for j in range(arr_.shape[1]):
        if arr_[i,j] %2 != 0:
            impar.append(arr_[i,j])
            
print(impar,'\n')
soma = sum(impar)
print(soma)


[1, 3, 5, 7, 9] 

25


In [189]:
print(arr_.shape[0])
print(arr_.shape[1])
print(arr_.shape)

3
3
(3, 3)
